language: ruby
sudo: false
cache: bundle
before_install: gem install bundler -v 1.10.6

rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2

script:
  - rake db:migrate
  - rake test

gemfile:
  - Gemfile
  # - gemfiles/Gemfile
